### ISSUE TITLE
Explaination and Reference needed.

### ISSUE THREAD

**Issue by EthanLifeGreat** [marcelo-caetano/sinusoidal-model#1]
The project can run perfectly on my computer. But I am interested in the two following questions:

1. In Line 74 in sof.m, what is the meaning of dividing the window by a factor of sum of the window? And how can this preserve the energy?

2. In Line 36 in stationary_synthesis.m, why is the meaning of the "2" before the amps? Also, I would appreciate it if you can provide some literature about the "Stationary Synthesis" as I failed to find papers about this procedure.

**Comment by marcelo-caetano** [comment]
Hi Ethan,
First off, thanks for your interest. This morning, I started writing an elaborate reply to your questions directly in the reply field only to lose everything. I should know better... Anyway, I'm going to give you a shorter answer to your questions and point you to the resources that support the explanations and will (hopefully) help you understand the answers.
The very short answer to both questions is "because I use the DFT (actually, the STFT) for spectral analysis". More details and links below.
1) The comments around line 74 (70, 72, and 76) summarize the reason. The DFT coefficients (see https://en.wikipedia.org/wiki/Discrete_Fourier_transform and https://www.mathworks.com/help/signal/ug/discrete-fourier-transform.html) are the result of a sum across N time samples. So, increasing N results in higher spectral amplitudes. The inverse DFT divides by N to compensate for that and give back the same temporal amplitude. Particularly, the zero-frequency DFT coefficient $X_0$ is $sum_{n=0}^{N-1}x_n$ (the signal energy is proportional to $X_0$, see https://en.wikipedia.org/wiki/Parseval%27s_theorem). In short, normalizing the time-signal eliminates the effect of N in the DFT spectrum, which is where the (sinusoidal) analysis happens.
The code uses a tapering window $w(n)$ (https://en.wikipedia.org/wiki/Window_function) for spectral analysis. Line 74 guarantees that the window by itself will sum to 1 and normalize the DFT. The code provides the flag 'NORMFLAG' to turn this window normalization ON or OFF. Try changing it for different windows and see the result. Particularly, the rectangular window is equivalent to multiplying $x(n)$ (the signal inside the frame) by 1, so no change in amplitude in the time domain. Create a synthetic sinusoid with known amplitude and see the resulting amplitude of the corresponding peak in the DFT spectrum to be convinced that only normalization will give the expected time-domain amplitude in the DFT spectrum.
2) The underlying reason is the same as before. The first half of the DFT spectrum corresponds to positive frequencies and the second half to negative frequencies. The code uses the positive half for the analysis (ignoring the spectral energy in the negative half). The amplitudes retrieved from the positive half must be doubled to retrieve the original signal upon resynthesis. See line 30 of 'sinusoidal_analysis.m', the indices are 1:nfft/2+1 corresponding to the positive half of the spectrum (plus zero frequency, the first coefficient for the reason in my first answer). The function 'sinusoidal_analysis.m' passes the positive half of the DFT to 'sinusoidal_analysis_frame.m' and from then on this must be compensated in the resynthesis process.
Finally, I did not use one specific article to implement 'stationary_synthesis.m', just general knowledge of audio processing (I personally recommend [1] for that). The underlying method of that particular function is overlap-add (OLA), so I suppose you could look at articles about OLA in sound analysis/synthesis, such as [2] and [3]. Finally, [4] is my recommendation for windows and the DFT. You will find more information in my publications here https://sites.google.com/view/marcelocaetano. See the publications page and the links to academic resources (Orcid, etc).
[1] A.V. Oppenheim, R.W. Schafer, Discrete-Time Signal Processing, Prentice-Hall, Upper Saddle River, NJ, USA, 1988.
[2] George, E.B., Smith, M.J.T.: Speech analysis/synthesis and modication using an analysis-by-synthesis/overlap-add sinusoidal model. IEEE Trans. Speech Audio Process. 5(5), 389-406 (Sep 1997)

[3] George, E.B., Smith, M.J.: Analysis-by-synthesis/overlap-add sinusoidal modeling applied to the analysis and synthesis of musical tones. J. Audio Eng. Soc 40(6), 497-516 (1992)

[4] F.J. Harris, On the use of windows for harmonic analysis with the discrete Fourier transform, Proc. IEEE 66 (1) (1978) 51–83.

**Comment by marcelo-caetano** [comment]
By the way, I forgot to mention that I'm actively developing the code now and will release an improved version soon. So keep an eye out for updates if you're interested.

**Comment by EthanLifeGreat** [comment]
Thanks a lot, Dr. Caetano.
